# Generated by Django 5.0.2 on 2024-03-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificate/'),
        ),
    ]
